### ISSUE TITLE
Dupe Bug with Auto Workbench 

### ISSUE THREAD

**Issue by lLuckyLukel** [FrogCraft/FrogCraft#6]
Sry for my bad english, cause i from Ukraine, but never mind >.< 
Well, u must watching this video, cause in this video dupe with auto workbench from your addon...v 1.1.
http://www.youtube.com/watch?v=cw_tJ4qYbXg

**Comment by rikka0w0** [comment]
Already fixed this bug~

**Comment by lLuckyLukel** [comment]
Wow, ok, it's good.
